#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
#

image:
  repository: fazalfarhan01/earnapp
  pullPolicy: Always
  tag: lite-1.269.378 #fazalfarhan01/earnapp

strategy:
  type: Recreate

env: []

args: []
  # - "--debug"

service:
  main:
    enabled: false

ingress:
  main:
    enabled: false

probes:
  liveness:
    enabled: false
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10
  readiness:
    enabled: false
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10
  startup:
    enabled: false
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10

securityContext:
  privileged: true

persistence:
  cgroup:
    enabled: true
    type: hostPath
    hostPath: /sys/fs/cgroup
    accessMode: ReadWriteOnce
    size: 1Gi